### PR TITLE
Integrate keyboard mapping

### PR DESCRIPTION
**Pull request by Guy-Adler**

### CODE REVIEW

**Comment by nicolas377** [comment]
I won't review this until I test it out later today.

**Comment by Guy-Adler** [comment]
It should be working well now, both with keyboard mapping and without.

**Comment by nicolas377** [comment]
Is there a way to have keyboard mapping running, but not spoiler arming?

**Comment by Guy-Adler** [comment]
Yeah
Might need to make it so that the UI only renders the spoilers arming keybind if it is on (it gets it from the local storage)

**Review by nicolas377 — APPROVED** [review]

**Comment by nicolas377** [comment]
I'll have to work on infrastructure once it gets merged into release

**Pull request merged**
